package main

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/kuan0808/cliproxy-kit/plugin/core"
)

func TestRequestsWithoutASessionShareOneRow(t *testing.T) {
	shares := map[string]*core.Share{
		"lcp:v1:aa": {Session: "lcp:v1:aa", Used: 0.01, Requests: 2, Last: 5},
		"lcp:v1:bb": {Session: "lcp:v1:bb", Used: 0.02, Requests: 1, Last: 9},
	}
	got := groupByProject(shares, nil, nil, nil, map[string]projectRef{"": {}})
	if len(got) != 1 || len(got[0].Sessions) != 1 {
		t.Fatalf("projects = %+v", got)
	}
	if s := got[0].Sessions[0]; s.ID != "" || s.Requests != 3 || got[0].Last != 9 {
		t.Fatalf("session = %+v", s)
	}
}

func near(a, b float64) bool { return math.Abs(a-b) < 1e-9 }

// Among all providers, requests without a session still carry each provider's part.
func TestEachProvidersPartFollowsTheListedSession(t *testing.T) {
	shares, usedBy := map[string]*core.Share{}, map[string]map[string]float64{}
	addProvider(shares, usedBy, "claude", core.Attribution{Sessions: map[string]*core.Share{
		"lcp:v1:aa": {Used: 0.01, Requests: 1, Metered: true},
		"lcp:v1:bb": {Used: 0.02, Requests: 1, Metered: true},
	}}, 2)
	got := groupByProject(shares, nil, usedBy, nil, map[string]projectRef{"": {}})
	if len(got) != 1 || !near(got[0].UsedBy["claude"], 0.03) || !near(got[0].Sessions[0].UsedBy["claude"], 0.03) {
		t.Fatalf("projects = %+v", got)
	}
}

func TestConversationTurns(t *testing.T) {
	for body, want := range map[string]bool{
		`{"tools":[{"name":"Bash"}],"metadata":{"user_id":"{\"session_id\":\"s1\"}"}}`:                     true,
		`{"tools":[],"metadata":{"user_id":"{\"session_id\":\"s1\"}"}}`:                                    false, // a permission check
		`{"tools":[{"name":"Read"}],"metadata":{"user_id":"{\"session_id\":\"s1\",\"agent_id\":\"a1\"}"}}`: false, // a subagent
		`{"tools":[{"name":"Read"}],"metadata":{"user_id":"user_x_session_s1","parent_session_id":"p"}}`:   false,
	} {
		if got := conversationTurn([]byte(body)); got != want {
			t.Errorf("conversationTurn(%s) = %v", body, got)
		}
	}
}

// The host reads agent_id "main" as the main conversation, and so does the plugin.
func TestTheMainAgentIsNotASubagent(t *testing.T) {
	body := `{"tools":[{"name":"Bash"}],"metadata":{"user_id":"{\"session_id\":\"s1\",\"agent_id\":\"main\"}"}}`
	if !conversationTurn([]byte(body)) {
		t.Fatal("a main-agent turn read as a subagent's")
	}
}

func TestRequestTitlesSkipWhatClientsPrepend(t *testing.T) {
	for want, texts := range map[string][]string{
		"Round 2 of a READ-ONLY plan review.": {"# AGENTS.md instructions for /x", "<environment_context> <cwd>/x</cwd>", "<task> Round 2 of a READ-ONLY plan review.\nmore"},
		"RELEASE_OP: v1 launch brief":         {"\u2063RELEASE_OP: v1 launch brief"},
		"":                                    {"<user_instructions>be brief</user_instructions>"},
		"Review round 3":                      {"<recommended_plugins>Here is a list of plugins that are available</recommended_plugins>", "<task>Review round 3</task>"},
		"Round 2 of a plan review.":           {"Codex Companion Task: <task> Round 2 of a plan review.\nmore"},
		"Fix the login page":                  {"Caveat: The messages below were generated by the user while running local commands.", "<command-name>/model</command-name>", "Fix the login page"},
	} {
		if got := requestTitle(texts); got != want {
			t.Errorf("requestTitle(%q) = %q, want %q", texts, got, want)
		}
	}
}

func TestProjectsAreRepositories(t *testing.T) {
	root := t.TempDir()
	main := filepath.Join(root, "voice-notes")
	sub := filepath.Join(main, "docs", "notes")
	tree := filepath.Join(root, "worktrees", "01M1XPYN7YRWWX1HXGY0WTY0P1")
	for _, d := range []string{filepath.Join(main, ".git", "worktrees", "w1"), sub, tree} {
		if err := os.MkdirAll(d, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	os.WriteFile(filepath.Join(tree, ".git"), []byte("gitdir: "+filepath.Join(main, ".git", "worktrees", "w1")+"\n"), 0o600)
	plain := filepath.Join(root, "notes")
	os.MkdirAll(plain, 0o700)
	for cwd, want := range map[string]string{sub: main, tree: main, main: main, plain: plain} {
		if got, repo := gitRoot(cwd); got != want || repo != (cwd != plain) {
			t.Errorf("gitRoot(%s) = %s %v, want %s", cwd, got, repo, want)
		}
	}
	if got := cleanTitle("\u2063Plan review, round 2\nsecond line"); got != "Plan review, round 2" {
		t.Errorf("cleanTitle = %q", got)
	}
}

func TestProjectsAreTheFoldersSessionsRanIn(t *testing.T) {
	home := "/Users/me"
	refs := mergeProjects(map[string]sessionInfo{
		"a": {Project: "web-app", Path: home + "/dev/web-app"},
		"b": {Project: "docs", Path: home + "/dev/web-app/docs"},                   // a subfolder, no repository
		"c": {Project: "docs", Path: home + "/dev/kit/docs"},                       // another docs, kit itself unseen
		"d": {Project: "docs", Path: home + "/other/docs"},                         // and a third
		"e": {Project: "~", Path: home},                                            // home
		"f": {Project: "notes", Path: home + "/notes"},                             // in home, which names no one
		"g": {Project: "voice-notes", Path: home + "/dev/voice-notes", Repo: true}, // a repository
		"h": {Project: "voice-notes", Repo: true},                                  // a removed worktree, known by its remote
		"i": {Project: "panel", Path: home + "/dev/voice-notes/panel", Repo: true}, // a nested repository stays apart
		"j": {},                                                                    // no transcript here
		"k": {Project: "Documents", Path: home + "/Documents"},                     // a session started in a folder of folders
		"l": {Project: "ambient", Path: home + "/Documents/dev/ambient"},           // which takes no project under it
	}, home)
	want := map[string]string{
		"a": "web-app", "b": "web-app/docs", "c": "kit/docs", "d": "other/docs", "e": "~",
		"f": "notes", "g": "voice-notes", "h": "voice-notes", "i": "panel", "j": "", "k": "Documents", "l": "ambient",
	}
	for id, name := range want {
		if refs[id].Name != name {
			t.Errorf("session %s: project %q, want %q", id, refs[id].Name, name)
		}
	}
	// Only a repository gathers what ran inside it; a folder outside one is its own project.
	if refs["b"].Path != home+"/dev/web-app/docs" || refs["l"].Path != home+"/Documents/dev/ambient" ||
		refs["h"].Path != home+"/dev/voice-notes" {
		t.Errorf("paths: %+v %+v %+v", refs["b"], refs["l"], refs["h"])
	}
}

func TestClaudeTranscriptHead(t *testing.T) {
	path := filepath.Join(t.TempDir(), "s.jsonl")
	body := `{"type":"queue-operation","content":"` + strings.Repeat("y", 300<<10) + `"}` + "\n" +
		`{"type":"user","entrypoint":"sdk-py","cwd":"/x/repo","message":{"role":"user","content":"<system-reminder>be good</system-reminder>"}}` + "\n" +
		`{"type":"user","cwd":"/x/repo","message":{"role":"user","content":[{"type":"text","text":"Caveat: local command"},{"type":"text","text":"Summarize the release notes\nplease"}]}}` + "\n"
	os.WriteFile(path, []byte(body), 0o600)
	h := readTranscriptHead(path)
	if h.cwd != "/x/repo" || h.entrypoint != "sdk-py" || h.prompt != "Summarize the release notes" {
		t.Fatalf("head = %+v", h)
	}
}

func TestScopesCountEachAccountsOwnPeriod(t *testing.T) {
	week := &reading{
		froms: map[string]int64{"d": 100, "k": 200, "cx": 150},
		owner: map[string]string{"d": "claude", "k": "claude", "cx": "codex"},
	}
	lines := []core.LogEntry{
		{T: 150, Account: "d"}, {T: 150, Account: "k"}, // k's week has not begun at 150
		{T: 250, Account: "k"}, {T: 160, Account: "cx"}, {T: 90, Account: "d"},
		{T: 300, Provider: "claude", History: true}, {T: 300, Account: "chatgpt:x", Provider: "codex"},
	}
	count := func(r *reading, scope string) int {
		in, _, ok := r.covers(scope)
		if !ok {
			return -1
		}
		n := 0
		for _, e := range lines {
			if in(e) {
				n++
			}
		}
		return n
	}
	for scope, want := range map[string]int{"all": 3, "provider:claude": 2, "d": 1, "k": 1, "cx": 1, "provider:nope": -1, "nope": -1} {
		if got := count(week, scope); got != want {
			t.Errorf("week, scope %s counts %d, want %d", scope, got, want)
		}
	}
	// Over a range a provider also counts lines without a known account; one account does not.
	// A provider listed without an account of its own still answers for its tokens.
	ranged := &reading{from: 100, froms: map[string]int64{"d": 100, "k": 100, "cx": 100}, owner: week.owner,
		providers: []usageProvider{{Provider: "claude"}, {Provider: "codex"}, {Provider: "gemini"}}}
	for scope, want := range map[string]int{"all": 6, "provider:claude": 4, "provider:codex": 2, "d": 1, "provider:gemini": 0, "provider:nope": -1} {
		if got := count(ranged, scope); got != want {
			t.Errorf("range, scope %s counts %d, want %d", scope, got, want)
		}
	}
}

// The panel reads each provider's part of a row from "used_by".
func TestRowsNameEachProvidersPartForThePanel(t *testing.T) {
	body, _ := json.Marshal(usageProject{UsedBy: map[string]float64{"codex": 0.1},
		Sessions: []usageSession{{UsedBy: map[string]float64{"claude": 0.2}}}})
	if n := strings.Count(string(body), `"used_by":`); n != 2 {
		t.Fatalf("used_by appears %d times in %s", n, body)
	}
}

// Projects of one name stay apart however many parent folders they share.
// A name made for a nested folder and one made to tell two projects apart must not meet: the
// report sums by name, so two projects would show as one.
func TestEveryProjectNameIsItsOwn(t *testing.T) {
	refs := mergeProjects(map[string]sessionInfo{
		"p": {Project: "p", Path: "/a/p"},
		"n": {Project: "c", Path: "/a/p/c"}, // named p/c after its parent
		"x": {Project: "c", Path: "/b/p/c", Repo: true},
		"y": {Project: "c", Path: "/d/q/c", Repo: true},
	}, "/home")
	seen := map[string]string{}
	for id, ref := range refs {
		if other, ok := seen[ref.Name]; ok {
			t.Fatalf("%s and %s both named %q: %+v", id, other, ref.Name, refs)
		}
		seen[ref.Name] = id
	}
}

func TestProjectsOfOneNameStayApart(t *testing.T) {
	refs := mergeProjects(map[string]sessionInfo{
		"s1": {Project: "repo", Path: "/a/team/repo", Repo: true},
		"s2": {Project: "repo", Path: "/b/team/repo", Repo: true},
		"s3": {Project: "repo", Path: "/c/repo", Repo: true},
	}, "/home")
	if refs["s1"].Name != "a/team/repo" || refs["s2"].Name != "b/team/repo" || refs["s3"].Name != "c/repo" {
		t.Fatalf("names = %+v", refs)
	}
	// Home is shown as "~", and so is a folder named "~": only their whole paths tell them apart.
	refs = mergeProjects(map[string]sessionInfo{
		"h": {Project: "~", Path: "/Users/me"},
		"t": {Project: "~", Path: "/Users/~"},
	}, "/Users/me")
	if refs["h"].Name == refs["t"].Name {
		t.Fatalf("names = %+v", refs)
	}
}

func TestAccountsOffTheProxyAreMaskedLikeItsOwn(t *testing.T) {
	for id, want := range map[string]string{
		"claude-0a0b0c0d-dana@example.com.json": "d•••",
		"codex-x":                               "c•••",
	} {
		if got := offProxyLabel(id); got != want {
			t.Errorf("%s = %q, want %q", id, got, want)
		}
	}
}

// Lines the disk refuses come back to be written on the next pass.
func TestLinesTheDiskRefusesComeBack(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := usageDir()
	if err := os.Chmod(dir, 0o500); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(dir, 0o700)
	lines := []core.LogEntry{{T: 1}, {T: 2}}
	if failed := appendLines("", lines); len(failed) != 2 {
		t.Fatalf("a refused write kept %d of 2 lines", len(failed))
	}
	_ = os.Chmod(dir, 0o700)
	if failed := appendLines("", lines); len(failed) != 0 {
		t.Fatalf("a write that went through returned %d lines", len(failed))
	}
}

// A transcript is read again once it changed, and only then.
func TestSessionTitlesFollowTheirTranscript(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	dir := filepath.Join(home, ".claude", "projects", "p")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "title-test.jsonl")
	write := func(title string) {
		if err := os.WriteFile(path, []byte(`{"type":"user","cwd":"/tmp","aiTitle":"`+title+`"}`+"\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	write("First")
	metaMu.Lock()
	indexedAt = time.Time{}
	metaMu.Unlock()
	if got := sessionMeta("title-test").Title; got != "First" {
		t.Fatalf("title = %q", got)
	}
	write("Second title")
	if got := sessionMeta("title-test").Title; got != "Second title" {
		t.Fatalf("after the transcript changed, title = %q", got)
	}
}

// A refresh reads an account again only once it was last read a minute ago or more.
func TestARefreshReadsAnAccountAtMostOnceAMinute(t *testing.T) {
	now := time.Now()
	for _, c := range []struct {
		at   time.Time
		want bool
	}{{time.Time{}, true}, {now.Add(-30 * time.Second), false}, {now.Add(-minRepoll), true}} {
		if got := due(c.at, now, minRepoll); got != c.want {
			t.Errorf("read %v ago: due %v, want %v", now.Sub(c.at), got, c.want)
		}
	}
	if !due(now, now, 0) {
		t.Error("the loop's own poll reads every account")
	}
}

// A day lists what its requests ran and its largest sessions: those readings tell by their part
// first, then the rest by weight.
func TestADayNamesItsLargestSessions(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	core.DayOf = func(ms int64) string { return "2026-10-05" }
	defer func() { core.DayOf = func(ms int64) string { return time.UnixMilli(ms).Format("2006-01-02") } }()
	now := time.Date(2026, 10, 5, 12, 0, 0, 0, time.Local)
	a := core.Attribution{Sessions: map[string]*core.Share{
		"small":   {Days: map[string]float64{"2026-10-05": 0.01}},
		"big":     {Days: map[string]float64{"2026-10-05": 0.05}},
		"settled": {Days: map[string]float64{"2026-10-05": 0}},
	}}
	use := map[string]*dayUse{"2026-10-05": {requests: 7, tokens: core.TokenSum{Output: 30},
		weights: map[string]float64{"small": 1, "big": 1, "settled": 1, "unread": 99}}}
	got := days(a, use, map[string]projectRef{}, now.UnixMilli(), now)
	if len(got) != 1 || got[0].Requests != 7 || got[0].Tokens.Output != 30 || len(got[0].Sessions) != 3 {
		t.Fatalf("days = %+v", got)
	}
	ids := []string{got[0].Sessions[0].ID, got[0].Sessions[1].ID, got[0].Sessions[2].ID}
	if ids[0] != "big" || ids[1] != "small" || ids[2] != "settled" || *got[0].Sessions[2].Used != 0 {
		t.Fatalf("largest = %v", ids)
	}
}

// After a restart the proxy has read no quota yet, so its state knows no weekly window; the log
// does. Placing the week a week before now instead would take the last window's readings in and
// call the new window's first reading use outside the proxy.
func TestTheWeekComesFromTheLogUntilTheProxyReadsAgain(t *testing.T) {
	const day = 24 * time.Hour
	now := time.Date(2026, 10, 6, 3, 0, 0, 0, time.UTC)
	reset := time.Date(2026, 10, 11, 12, 0, 0, 0, time.UTC) // this window: 10/4 12:00 to 10/11 12:00
	used := func(f float64) *float64 { return &f }
	ms := func(tm time.Time) int64 { return tm.UnixMilli() }
	lines := []core.LogEntry{
		// The window before, nearly used up.
		{T: ms(reset.Add(-8 * day)), Account: "a", Provider: "claude", Poll: true, Used7d: used(0.9), Reset7: ms(reset.Add(-7 * day))},
		// This window: a reading at 0, then a session's request and the reading after it.
		{T: ms(reset.Add(-6 * day)), Account: "a", Provider: "claude", Poll: true, Used7d: used(0), Reset7: ms(reset)},
		{T: ms(reset.Add(-6*day + time.Hour)), Account: "a", Provider: "claude", Session: "s", Output: 1000},
		{T: ms(reset.Add(-6*day + 2*time.Hour)), Account: "a", Provider: "claude", Poll: true, Used7d: used(0.1), Reset7: ms(reset)},
	}
	attribute := func(info core.AccountInfo) core.Attribution {
		ws := weekStart(info, now).UnixMilli()
		return core.Attribute(lines, "a", core.Span{From: ws - core.WindowJitter, To: ms(now), CountFrom: ws - core.WindowJitter, LogStart: lines[0].T, WindowStart: ws})
	}
	info := windowOf(core.AccountInfo{ID: "a", Provider: "claude"}, lines, now)
	if !info.ResetAt.Equal(reset) {
		t.Fatalf("reset = %v, want %v", info.ResetAt, reset)
	}
	// The same parts as once the proxy has read the account itself.
	got, want := attribute(info), attribute(core.AccountInfo{ID: "a", Provider: "claude", ResetAt: reset})
	if !near(got.Used, 0.1) || !near(got.Sessions["s"].Used, want.Sessions["s"].Used) ||
		!near(got.Outside, want.Outside) || !near(got.BeforeLog, want.BeforeLog) {
		t.Fatalf("from the log %+v, read by the proxy %+v", got, want)
	}
	// What the proxy read itself stands; a window the log saw end rolls on by whole weeks.
	own := time.Date(2026, 10, 12, 0, 0, 0, 0, time.UTC)
	if got := windowOf(core.AccountInfo{ID: "a", ResetAt: own}, lines, now); !got.ResetAt.Equal(own) {
		t.Fatalf("own reset = %v", got.ResetAt)
	}
	if got := windowOf(core.AccountInfo{ID: "a"}, lines, reset.Add(8*day)); !got.ResetAt.Equal(reset.Add(14 * day)) {
		t.Fatalf("rolled reset = %v", got.ResetAt)
	}
}

// A window that started over just before its reset is listed once, as the running one.
func TestFiveHourListsARunningWindowOnce(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	now := time.Date(2026, 10, 7, 12, 0, 0, 0, time.UTC)
	ms := func(d time.Duration) int64 { return now.Add(d).UnixMilli() }
	used := func(f float64) *float64 { return &f }
	reset := ms(time.Minute)
	line := func(at time.Duration, session string, u5 float64) core.LogEntry {
		return core.LogEntry{T: ms(at), Account: "a", Provider: "claude", Session: session, Output: 100,
			Poll: session == "", Used5h: used(u5), Reset5: reset}
	}
	lines := []core.LogEntry{line(-4*time.Hour, "", 0.30), line(-time.Minute, "", 0.30),
		line(-30*time.Second, "s1", 0), line(-10*time.Second, "", 0.01)}
	u := &reading{week: map[string]core.Attribution{}, ranged: map[string]core.Attribution{}, froms: map[string]int64{}, starts: map[string]int64{},
		owner: map[string]string{}, windows: map[string][]fiveWindow{}, noWindow: map[string]bool{}, namedFrom: map[string]int64{}}
	u.fiveHour(core.AccountInfo{ID: "a", Provider: "claude"}, lines, lines[0].T, now, nil)
	if list := u.windows["a"]; len(list) != 2 || list[0].running || !list[1].running {
		t.Fatalf("windows = %+v", list)
	}
}

// The host names "auto" when a client asks for no tier; the log keeps none then. A provider that
// reports "auto" is taken at its word.
func TestATierIsKeptAsAskedOrNone(t *testing.T) {
	if askedTier(" Priority ") != "priority" || askedTier("auto") != "" || askedTier("") != "" || tierOf("Auto") != "auto" {
		t.Fatal("tiers")
	}
}

// A Claude plan is read again an hour on, on a refresh, and after a window started over in place.
func TestAPlanIsReadAgainWhenItMayHaveChanged(t *testing.T) {
	now := time.Date(2026, 10, 7, 6, 30, 0, 0, time.UTC)
	read := now.Add(-10 * time.Minute)
	switch {
	case !planDue(time.Time{}, time.Time{}, now, false):
		t.Fatal("never read: not due")
	case planDue(read, time.Time{}, now, false):
		t.Fatal("read 10 minutes ago: due")
	case !planDue(now.Add(-planTTL), time.Time{}, now, false):
		t.Fatal("read an hour ago: not due")
	case !planDue(read, time.Time{}, now, true):
		t.Fatal("refresh: not due")
	case !planDue(read, read.Add(time.Minute), now, false):
		t.Fatal("started over since the read: not due")
	case planDue(read, read.Add(-time.Minute), now, false):
		t.Fatal("started over before the read: due")
	}
}

// Over 5h an account shows its running window as the week range shows its week, from where it
// started over in place, and the windows of the last day beside it; readings that do not name their
// reset list no window.
func TestFiveHourShowsTheRunningWindowAndTheLastDays(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	now := time.Date(2026, 10, 7, 12, 0, 0, 0, time.UTC)
	ms := func(d time.Duration) int64 { return now.Add(d).UnixMilli() }
	used := func(f float64) *float64 { return &f }
	r1, r2 := ms(-5*time.Hour), ms(2*time.Hour)
	line := func(at time.Duration, session string, u5 *float64, reset int64) core.LogEntry {
		return core.LogEntry{T: ms(at), Account: "a", Provider: "claude", Session: session, Output: 100, Poll: session == "", Used5h: u5, Reset5: reset}
	}
	lines := []core.LogEntry{
		line(-20*time.Hour, "", used(0.5), 0), // no reset named: no window of its own
		// Watched closely: the rise is the request's.
		line(-10*time.Hour, "", used(0), r1),
		line(-10*time.Hour+10*time.Minute, "s1", nil, 0),
		line(-10*time.Hour+20*time.Minute, "", used(0.30), r1),
		line(-2*time.Hour, "s2", nil, 0),
		line(-1*time.Hour, "", used(0.10), r2),
		line(-30*time.Minute, "", used(0), r2), // started over in place, and held
		line(-20*time.Minute, "s3", nil, 0),
		line(-10*time.Minute, "", used(0.05), r2),
	}
	u := &reading{week: map[string]core.Attribution{}, ranged: map[string]core.Attribution{}, froms: map[string]int64{}, starts: map[string]int64{},
		owner: map[string]string{}, windows: map[string][]fiveWindow{}, noWindow: map[string]bool{}, namedFrom: map[string]int64{}}
	acct := u.fiveHour(core.AccountInfo{ID: "a", Provider: "claude"}, lines, lines[0].T, now, nil)
	if !near(acct.Used, 0.05) || !acct.Known || acct.NoWindow || acct.ResetAt.UnixMilli() != r2 || acct.RestartedAt != ms(-time.Hour) {
		t.Fatalf("account = %+v", acct)
	}
	if s := u.ranged["a"].Sessions; s["s2"] != nil || !near(s["s3"].Used, 0.05) {
		t.Fatalf("running window sessions = %+v", s)
	}
	// Its tokens count from the fall, as no request since the last rise is left; it shows from the
	// last reading before the fall.
	if u.froms["a"] != ms(-30*time.Minute) || u.starts["a"] != ms(-time.Hour) {
		t.Fatalf("counts from %v, shows from %v", u.froms["a"], u.starts["a"])
	}
	list := u.windows["a"]
	if len(list) != 3 || u.namedFrom["a"] != ms(-10*time.Hour) {
		t.Fatalf("windows = %+v, named from %v", list, u.namedFrom["a"])
	}
	first, cut, running := list[0], list[1], list[2]
	if first.From != r1-core.FiveMs || windowEnd(first.Period) != r1 || !near(first.Used, 0.30) || !near(first.Parts["s1"], 0.30) || first.running {
		t.Fatalf("first window = %+v", first)
	}
	if windowEnd(cut.Period) != ms(-time.Hour) || !near(cut.Used, 0.10) || !near(cut.Parts["s2"], 0.10) {
		t.Fatalf("window cut short = %+v", cut)
	}
	if !running.running || running.From != ms(-time.Hour) || windowEnd(running.Period) != r2 || !near(running.Parts["s3"], 0.05) {
		t.Fatalf("running window = %+v", running)
	}
	// An idle account loses no window, whether or not the provider names a reset for it: one that
	// used nothing and served no request is not running.
	idle := []core.LogEntry{{T: ms(-time.Hour), Account: "i", Provider: "claude", Poll: true, Used5h: used(0)},
		{T: ms(-time.Minute), Account: "i", Provider: "claude", Poll: true, Used5h: used(0), Reset5: ms(5 * time.Hour)}}
	acct = u.fiveHour(core.AccountInfo{ID: "i", Provider: "claude"}, idle, idle[0].T, now, nil)
	if acct.NoWindow || !acct.Known || !acct.ResetAt.IsZero() || len(u.windows["i"]) != 0 || u.namedFrom["i"] != 0 {
		t.Fatalf("idle = %+v, windows %v, named from %v", acct, u.windows["i"], u.namedFrom["i"])
	}
	// A recent reading that used some and named no reset (an older log's) leaves it unknown.
	older := []core.LogEntry{{T: ms(-time.Hour), Account: "o", Provider: "claude", Poll: true, Used5h: used(0.30)}}
	if acct = u.fiveHour(core.AccountInfo{ID: "o", Provider: "claude"}, older, older[0].T, now, nil); acct.Known || acct.NoWindow {
		t.Fatalf("older = %+v", acct)
	}
	// An account read with a weekly window only has no 5-hour window; one not read at all is not known.
	weekly := []core.LogEntry{{T: ms(-time.Hour), Account: "cx", Provider: "codex", Poll: true, Used7d: used(0.20)}}
	codex := u.fiveHour(core.AccountInfo{ID: "cx", Provider: "codex"}, weekly, weekly[0].T, now, nil)
	if !codex.NoWindow || codex.Known || !u.noWindow["cx"] || len(u.windows["cx"]) != 0 {
		t.Fatalf("codex = %+v", codex)
	}
	if fresh := u.fiveHour(core.AccountInfo{ID: "n", Provider: "claude"}, nil, 0, now, nil); fresh.NoWindow || fresh.Known {
		t.Fatalf("not read = %+v", fresh)
	}
}
